server:
  port: 8080

spring:
  application:
      name: yong-security
  data:
    mongodb:
      uri: mongodb://${yong.mongodb.uri}:27017/security
      database: security
security:
  headers:
    content-type: true

logging:
  level:
    com.yong: DEBUG
    org.springframework.security: DEBUG

yong:
  oauth:
    enable: true
    resource: yong
  debug:
    enable: true
  mongodb:
    uri: mongodb
