server:
  port: 8081
#
spring:
  application:
      name: yong-security
  data:
    mongodb:
      uri: mongodb://localhost:27017/security
security:
  headers:
    content-type: true
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    statusPageUrlPath: /index

#logging:
#  level:
#    com.yong: DEBUG


