server:
  port: 8087
spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8087/.well-known/jwks.json
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?authSource=admin
      database: test


logging:
  level:
    com.yong: DEBUG
    org.springframework.security: DEBUG

yong:
  oauth:
    enable: true
    resource: yong
  debug:
    enable: true
  mongodb:
    uri: mongodb


management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

# application:
wechat:
  miniapp:
    appid: xxx
    secret: xxx
    msgDataFormat: JSON
    token: 111
    aesKey: 111

