server:
  port: 8081
  servlet:
    context-path: /api
#
spring:
  application:
      name: yong-security
  data:
    mongodb:
      uri: mongodb://localhost:27017/security
security:
  headers:
    content-type: true
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    statusPageUrlPath: /index

logging:
  level:
    com.yong: DEBUG
    org.springframework.security: INFO

yong:
  oauth:
#如果为false, 任何url都不校验, 方便测试一些与Security无关的接口
    enable: false
  debug:
#如果为true,在报错的时候,将报错信息直接塞到ResponseVO的data里面,方便查看
    enable: true
