server:
  port: 8081

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          okta:
#            client-id: first-client
#            client-secret: noonewilleverguess
#            authorization-grant-type: password
#            scope: any
#            provider: okta
#            client-authentication-method: basic
#        provider:
#          okta:
#            token-uri: http://localhost:8087/api/oauth/token
#            user-info-uri: http://localhost:8087/api/user/info
#            authorization-uri: http://localhost:8087/api/oauth/authorize
#            user-name-attribute: first-client
#            user-info-authentication-method: header

logging:
  level:
    web: DEBUG
